"""
Fitting simulation parameters to a measured z-vertex distribution.

This example demonstrates the parameter-fitting workflow used in real Vernier
scan analyses:

1. **Generate a synthetic "measurement"** — run the simulation with known
   "true" parameters and add Poisson noise to create a realistic histogram.
2. **Fit the beam width** — scan over beam width values and minimise the
   RMS residual between simulation and data to recover the true value.
3. **Fit the crossing angle** — starting from the best beam width, use
   ``scipy.optimize.minimize_scalar`` to recover the true crossing angle.

Because the "measurement" is generated by the simulation itself, the example
is fully self-contained: no external data files are required.

For a real analysis, replace ``make_synthetic_measurement()`` with your own
function that returns ``(z_centers, counts)`` from measured data.

Run::

    python examples/fit_simulation_to_data.py
"""

import numpy as np
import matplotlib
import importlib

def _pick_backend():
    for name in ('TkAgg', 'Qt5Agg', 'Qt6Agg', 'WxAgg'):
        try:
            matplotlib.use(name)
            importlib.import_module(f'matplotlib.backends.backend_{name.lower()}')
            return name
        except Exception:
            continue
    matplotlib.use('Agg')
    return 'Agg'

_BACKEND = _pick_backend()
import matplotlib.pyplot as plt
from scipy.optimize import minimize_scalar
from scipy.interpolate import interp1d

from bunch_collider import BunchCollider, Measure


# -----------------------------------------------------------------------
# Shared simulation builder
# -----------------------------------------------------------------------

def build_sim(beam_width, beam_length, beta_star, z_initial,
              crossing_angle_x=0., crossing_angle_y=0.,
              x_offset=0., mbd_resolution=None):
    """
    Configure and return a BunchCollider with the given parameters.

    Parameters
    ----------
    beam_width : float
        Transverse RMS beam width (um).
    beam_length : float
        Longitudinal RMS bunch length (um).
    beta_star : float
        Beta* hourglass parameter (cm).
    z_initial : float
        Initial |z| position of each bunch (um).
    crossing_angle_x : float
        Crossing half-angle in the x-z plane (rad).
    crossing_angle_y : float
        Crossing half-angle in the y-z plane (rad).
    x_offset : float
        Transverse offset of bunch 1 in x (um).
    mbd_resolution : float or None
        If given, apply a Gaussian smear to the z distribution (cm).

    Returns
    -------
    BunchCollider
    """
    sim = BunchCollider()
    sim.set_bunch_rs(np.array([x_offset, 0., -z_initial]),
                     np.array([0.,       0.,  z_initial]))
    sim.set_bunch_sigmas(np.array([beam_width, beam_width]),
                         np.array([beam_width, beam_width]))
    sim.set_bunch_lengths(beam_length, beam_length)
    sim.set_bunch_beta_stars(beta_star, beta_star)
    sim.set_bunch_crossing(crossing_angle_x, 0., crossing_angle_y, 0.)
    if mbd_resolution is not None:
        sim.set_gaus_smearing_sigma(mbd_resolution)
    return sim


# -----------------------------------------------------------------------
# Synthetic measurement
# -----------------------------------------------------------------------

def make_synthetic_measurement(true_beam_width, true_crossing_angle,
                                beam_length, beta_star, z_initial,
                                mbd_resolution, n_counts=50_000,
                                n_bins=100, rng=None):
    """
    Generate a synthetic z-vertex histogram by running the simulation with
    "true" parameters and sampling from the resulting distribution.

    Parameters
    ----------
    true_beam_width : float
        True transverse RMS beam width (um).
    true_crossing_angle : float
        True crossing half-angle in the x-z plane (rad).
    beam_length, beta_star, z_initial, mbd_resolution : float
        Simulation physics parameters.
    n_counts : int
        Total number of simulated vertex counts.
    n_bins : int
        Number of z bins in the histogram.
    rng : np.random.Generator, optional
        Random number generator for reproducibility.

    Returns
    -------
    z_centers : np.ndarray
        Bin centres (cm).
    counts : np.ndarray
        Integer bin counts.
    """
    if rng is None:
        rng = np.random.default_rng(42)

    sim = build_sim(true_beam_width, beam_length, beta_star, z_initial,
                    crossing_angle_x=true_crossing_angle,
                    mbd_resolution=mbd_resolution)
    sim.run_sim_parallel()
    zs, z_dist = sim.get_z_density_dist()

    # Normalise to a probability density and sample
    pdf = np.maximum(z_dist, 0.)
    pdf /= np.trapezoid(pdf, zs)

    # Sample vertex positions from the pdf using inverse-CDF method
    cdf = np.cumsum(pdf) * (zs[1] - zs[0])
    cdf /= cdf[-1]
    u = rng.uniform(0., 1., n_counts)
    z_samples = np.interp(u, cdf, zs)

    z_range = (zs[0], zs[-1])
    counts, edges = np.histogram(z_samples, bins=n_bins, range=z_range)
    z_centers = 0.5 * (edges[:-1] + edges[1:])
    return z_centers, counts.astype(float)


# -----------------------------------------------------------------------
# Residual calculation
# -----------------------------------------------------------------------

def compute_residual(sim_zs, sim_dist, data_zs, data_counts):
    """
    Interpolate the simulation onto the data z-centres and compute the
    normalised RMS residual.

    Parameters
    ----------
    sim_zs, sim_dist : np.ndarray
        Simulation z positions (cm) and density.
    data_zs, data_counts : np.ndarray
        Data z bin centres (cm) and counts.

    Returns
    -------
    float
        Normalised RMS residual.
    """
    sim_interp = interp1d(sim_zs, sim_dist, bounds_error=False, fill_value=0.)
    sim_vals = sim_interp(data_zs)

    # Scale simulation to match total counts
    scale = np.sum(data_counts) / (np.sum(sim_vals) + 1e-30)
    sim_vals_scaled = sim_vals * scale

    rms = np.sqrt(np.mean((data_counts - sim_vals_scaled) ** 2))
    return rms / (np.mean(data_counts) + 1e-30)


# -----------------------------------------------------------------------
# Beam width scan
# -----------------------------------------------------------------------

def fit_beam_width(data_zs, data_counts, beam_widths,
                   beam_length, beta_star, z_initial,
                   mbd_resolution, crossing_angle_x=0.):
    """
    Scan over candidate beam widths and return the one with minimum residual.

    Parameters
    ----------
    data_zs, data_counts : np.ndarray
        Measured z-vertex histogram.
    beam_widths : np.ndarray
        Beam width values to try (um).
    beam_length, beta_star, z_initial, mbd_resolution : float
        Fixed simulation parameters.
    crossing_angle_x : float
        Fixed crossing angle (rad).

    Returns
    -------
    best_bw : float
        Best-fit beam width (um).
    residuals : np.ndarray
        Residual for each candidate width.
    """
    residuals = []
    for bw in beam_widths:
        sim = build_sim(bw, beam_length, beta_star, z_initial,
                        crossing_angle_x=crossing_angle_x,
                        mbd_resolution=mbd_resolution)
        sim.run_sim_parallel()
        zs, z_dist = sim.get_z_density_dist()
        residuals.append(compute_residual(zs, z_dist, data_zs, data_counts))
        print(f'  bw = {bw:.1f} um   residual = {residuals[-1]:.4f}')

    residuals = np.array(residuals)
    best_bw = beam_widths[np.argmin(residuals)]
    return best_bw, residuals


# -----------------------------------------------------------------------
# Crossing angle fit
# -----------------------------------------------------------------------

def fit_crossing_angle(data_zs, data_counts, best_bw,
                       beam_length, beta_star, z_initial, mbd_resolution,
                       angle_bounds=(-2e-3, 2e-3)):
    """
    Use ``scipy.optimize.minimize_scalar`` to find the crossing angle that
    minimises the residual between simulation and data.

    Parameters
    ----------
    data_zs, data_counts : np.ndarray
        Measured z-vertex histogram.
    best_bw : float
        Best-fit beam width from a prior beam-width scan (um).
    beam_length, beta_star, z_initial, mbd_resolution : float
        Fixed simulation parameters.
    angle_bounds : tuple of float
        (min, max) search range for the crossing angle (rad).

    Returns
    -------
    float
        Best-fit crossing angle (rad).
    """
    def objective(angle_x):
        sim = build_sim(best_bw, beam_length, beta_star, z_initial,
                        crossing_angle_x=angle_x,
                        mbd_resolution=mbd_resolution)
        sim.run_sim_parallel()
        zs, z_dist = sim.get_z_density_dist()
        return compute_residual(zs, z_dist, data_zs, data_counts)

    result = minimize_scalar(objective, bounds=angle_bounds, method='bounded',
                             options={'xatol': 1e-6})
    return result.x


# -----------------------------------------------------------------------
# Plotting helpers
# -----------------------------------------------------------------------

def scale_sim_to_data(sim_zs, sim_dist, data_zs, data_counts):
    """Scale and shift simulation to overlay on data (amplitude only)."""
    sim_interp = interp1d(sim_zs, sim_dist, bounds_error=False, fill_value=0.)
    sim_vals = sim_interp(data_zs)
    scale = np.sum(data_counts) / (np.sum(sim_vals) + 1e-30)
    return scale


# -----------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------

def main():
    # --- True parameters (unknown to the fitter) ---
    TRUE_BW = 162.           # um  true beam width
    TRUE_ANGLE = 0.1e-3      # rad true crossing half-angle
    BEAM_LENGTH = 1.1e6      # um
    BETA_STAR = 85.          # cm
    Z_INITIAL = 6.0e6        # um
    MBD_RESOLUTION = 2.0     # cm  detector smearing

    print("=" * 60)
    print("Generating synthetic measurement...")
    print(f"  True beam width:     {TRUE_BW:.1f} um")
    print(f"  True crossing angle: {TRUE_ANGLE * 1e3:.3f} mrad")
    print("=" * 60)

    data_zs, data_counts = make_synthetic_measurement(
        TRUE_BW, TRUE_ANGLE, BEAM_LENGTH, BETA_STAR, Z_INITIAL, MBD_RESOLUTION
    )

    # --- Step 1: beam width scan ---
    print("\n--- Step 1: beam width scan ---")
    beam_widths = np.arange(145., 185., 5.)   # coarse scan
    best_bw_coarse, residuals_coarse = fit_beam_width(
        data_zs, data_counts, beam_widths,
        BEAM_LENGTH, BETA_STAR, Z_INITIAL, MBD_RESOLUTION,
        crossing_angle_x=0.,   # ignore crossing angle in first pass
    )
    print(f"\nCoarse best beam width: {best_bw_coarse:.1f} um")

    # Fine scan around the coarse minimum
    bw_fine = np.arange(best_bw_coarse - 8., best_bw_coarse + 9., 2.)
    best_bw, residuals_fine = fit_beam_width(
        data_zs, data_counts, bw_fine,
        BEAM_LENGTH, BETA_STAR, Z_INITIAL, MBD_RESOLUTION,
        crossing_angle_x=0.,
    )
    print(f"Fine best beam width:   {best_bw:.1f} um  (true: {TRUE_BW:.1f} um)")

    # --- Step 2: crossing angle fit ---
    print("\n--- Step 2: crossing angle fit ---")
    best_angle = fit_crossing_angle(
        data_zs, data_counts, best_bw,
        BEAM_LENGTH, BETA_STAR, Z_INITIAL, MBD_RESOLUTION,
        angle_bounds=(-1e-3, 1e-3),
    )
    print(f"Best crossing angle: {best_angle * 1e3:.3f} mrad  "
          f"(true: {TRUE_ANGLE * 1e3:.3f} mrad)")

    # --- Build final simulation ---
    sim_final = build_sim(best_bw, BEAM_LENGTH, BETA_STAR, Z_INITIAL,
                          crossing_angle_x=best_angle,
                          mbd_resolution=MBD_RESOLUTION)
    sim_final.run_sim_parallel()
    zs_final, z_dist_final = sim_final.get_z_density_dist()
    scale = scale_sim_to_data(zs_final, z_dist_final, data_zs, data_counts)

    # Wrap key results in Measure for display
    bw_result = Measure(best_bw, 2.)            # ±2 um nominal uncertainty
    angle_result = Measure(best_angle * 1e3, 0.01)  # ±0.01 mrad

    # --- Plots ---
    bin_width = data_zs[1] - data_zs[0]
    fig, axes = plt.subplots(1, 3, figsize=(14, 4))

    # Panel 1: beam width scan residuals
    all_bws = np.concatenate([beam_widths, bw_fine])
    all_res = np.concatenate([residuals_coarse, residuals_fine])
    sort_idx = np.argsort(all_bws)
    axes[0].plot(all_bws[sort_idx], all_res[sort_idx], 'o-', color='steelblue')
    axes[0].axvline(best_bw, color='red', linestyle='--', label=f'Best: {best_bw:.0f} μm')
    axes[0].axvline(TRUE_BW, color='green', linestyle=':', label=f'True: {TRUE_BW:.0f} μm')
    axes[0].set_xlabel('Beam width (μm)')
    axes[0].set_ylabel('Normalised RMS residual')
    axes[0].set_title('Beam Width Scan')
    axes[0].legend(fontsize=8)
    axes[0].set_ylim(bottom=0)
    axes[0].grid(alpha=0.3)

    # Panel 2: final overlay
    axes[1].bar(data_zs, data_counts, width=bin_width, alpha=0.6,
                color='steelblue', label='Synthetic data')
    axes[1].plot(zs_final, z_dist_final * scale, 'r-', lw=2, label='Best-fit sim')
    axes[1].annotate(
        f'Fit:  σ = {bw_result} μm\n'
        f'      θ = {angle_result} mrad',
        xy=(0.04, 0.95), xycoords='axes fraction', va='top',
        fontsize=9, bbox=dict(facecolor='wheat', alpha=0.5),
    )
    axes[1].set_xlabel('z vertex (cm)')
    axes[1].set_ylabel('Counts')
    axes[1].set_title('Fit Result')
    axes[1].legend(fontsize=8)
    axes[1].set_ylim(bottom=0)
    axes[1].grid(alpha=0.3)

    # Panel 3: residuals vs z
    sim_interp = interp1d(zs_final, z_dist_final * scale,
                          bounds_error=False, fill_value=0.)
    residuals_z = data_counts - sim_interp(data_zs)
    axes[2].bar(data_zs, residuals_z, width=bin_width, color='gray', alpha=0.7)
    axes[2].axhline(0, color='black', lw=0.8)
    axes[2].set_xlabel('z vertex (cm)')
    axes[2].set_ylabel('Data − Simulation')
    axes[2].set_title('Fit Residuals')
    axes[2].grid(alpha=0.3)

    fig.tight_layout()
    if _BACKEND == 'Agg':
        out = "fit_simulation_to_data.png"
        fig.savefig(out, dpi=150, bbox_inches='tight')
        print(f"No interactive display found — figure saved to {out}")
    else:
        plt.show()


if __name__ == '__main__':
    main()
